### ISSUE TITLE
Is it possible to use this library in a non Angular Project?

### ISSUE THREAD

**Issue by davide-talesco** [vmware/vcd-ext-sdk#105]
I would like to use this library in my nodejs / typescript backend service, but it looks like it is highly coupled to Angular? Is it possible to use this library (javascript) if I am not using Angular?

**Comment by jmoroski** [comment]
As you've already noted this specific implementation is highly coupled to Angular, relying most heavily on the HttpClient for wire transfer and Angular injection constructs.

If you need this functionality in a purely backend service, it might be worthwhile to re-implement the basic API contract of `VcdApiClient` around a library like [Request](https://github.com/request/request). It would support submitting auth tokens and modifying request headers, and accessing full response, which is most of the functionality that the current implementation leverages through Angular constructs. It may not be a fully compatible API experience which returns rxjs Observables, but a Promise to Observable conversion is easy enough in RxJS 6+, or you may prefer working with Promises.

This work is not currently on our roadmap, because the main goal of this SDK is to enable UI plugins, and those UI plugins are best delivered as Angular-based Clarity applications. If you were to submit some code, I'd be happy to review it and see if it makes sense to include in the overall library.

**Comment by davide-talesco** [comment]
Hi, I am trying to rewrite like you suggested using Axios but I am having some issue when importing the bindings below:

```
import { SessionType, QueryResultRecordsType, AuthorizedLocationType, ResourceType, LinkType, EntityReferenceType, EntityType, TaskType } from '@vcd/bindings/vcloud/api/rest/schema_v1_5';
import { SupportedVersionsType } from '@vcd/bindings/vcloud/api/rest/schema/versioning';
```

```
/vcd-ext-sdk-sample/node_modules/@vcd/bindings/vcloud/api/rest/schema_v1_5/index.js:4
export * from './EventType';
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Do you know what am I doing wrong?

**Comment by jmoroski** [comment]
You mentioned previously that you're doing this in Node.js. @vcd/sdk and @vcd/bindings are es2015 modules. Does your package.json file need to specify `"type": "module"`? If you're pre-Node 13, you might also need to use the `--experimental-modules` flag

**Comment by davide-talesco** [comment]
ok, I got it working by compiling the bindings myself as commonJs modules.
Thanks!

**Comment by davide-talesco** [comment]
one more question: I don't quite understand if the bindings can be used to convert between XML representation and JS representation and viceversa? If yes can you point me out to the right direction on how to do the conversion?
