### ISSUE TITLE
SESSION_ORGANIZATION injected with incorrect letter case

### ISSUE THREAD

**Issue by tekiyang-dellcom** [vmware/vcd-ext-sdk#106]
**Describe the bug**
The Org name contains both upper and lower cased letters.
Enter Tenant Portal with all-lower-cased org name in the URL.
The plugin will get SESSION_ORGANIZATION injected from container as in an all-lower-cased form.

**To Reproduce**
1. Create an Org with mixed-cased name, say 'Org_Test'
2. Open browser with URL as 'https//vcloud-server/tenant/org_test'
3. Verify the injected SESSION_ORGANIZATION value to be as 'org_test'

**Expected behavior**
Expect it to be 'Org_Test'

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser  [chrome]
 - @vcd/sdk Version [0.11.0]
- vCloud Director Version [10.0]

**Additional context**
N/A

**Comment by ilesev-vmw** [comment]
This isn't an issue in the SDK per se. Can you provide a little more context? How is the mismatch in casing proving to be an issue for you?

**Comment by tekiyang-dellcom** [comment]
This issue existed in @vdc/sdk [0.9.0].
In 0.9.0, the container hooks provide only SESSION_ORG and not SESSION_ORG_ID, so our product depends on comparing SESSION_ORG with the result obtained from '/api/org' to get the org's UUID.
So when the injected name is case-incorrect, this action will fail.
I know 0.11.0 is actually alright since it provides SESSION_ORG_ID directly. But our product's last official release has been shipped with 0.9.0.
I guess this issue is in the container itself. I'm raising it here as the SDK is our interface with the container.
Thank you.

**Comment by ilesev-vmw** [comment]
If that's the case, I'd suggest doing a case-insensitive check. When you create an organization, the organization name (**_not_** the organization full name) is unique and case-insensitive, because in reality both .../tenant/org1 and .../tenant/OrG1 will be resolved to the same URL. 

Ideally, you'd be able to ship a new version with 0.11.0 containing the SESSION_ORG_ID and not extracting the organization id in such a roundabout and fragile way, but that seems hard in your case.

**Comment by tekiyang-dellcom** [comment]
If the org name is guaranteed unique in a case-insensitive way, we can modify our codes.
And yes, the next release will be based on direct SESSION_ORG_ID injection.
