### ISSUE TITLE
yarn package installation fails in vcd-plugin-seed

### ISSUE THREAD

**Issue by mgaruccio** [vmware/vcd-ext-sdk#60]
**Describe the bug**
attempting to run `yarn` within the vcd-plugin-seed folder fails and generates the error below.  

```
➜ yarn
yarn install v1.12.3
[1/4] Resolving packages...
error Package "" refers to a non-existing file '"/mnt/c/Users/mike.garuccio/code/vcd-ext-sdk/ui/api-client/packages/bindings/dist"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
1. clone the package from github
2. cd into vcd-ext-sdk/ui/vcd-plugin-seed
3. run `yarn`

**Expected behavior**
packages to successfully install

**Desktop (please complete the following information):**
 - OS: Ubuntu 1804 within Win10 WSL
 - Browser: n/a
 - Version: latest

**Additional context**
tried both within Windows Subsystem for Linux and natively within Windows 10 with the same error on both attempts.  also tried cloning the package again with no luck.

**Comment by jmoroski** [comment]
At the moment, building the plugin seed requires building the rest of the project (this should probably be indicated in the Prerequisites). This is because @vcd/sdk and @vcd/bindings are not yet available in NPM. The package.json is correctly referencing the package paths but they don't exist until they have been built.

We understand that this is an inconvenience, and are currently in the process of getting distributions of this entire repo into publicly accessible Maven and NPM locations.

In the meantime, the prerequisites can be built by first executing
`mvn install -Dcheckstyle.skip` from the java/api-schemas directory, and then building the @vcd/sdk and @vcd/bindings packages as outlined here:
https://github.com/vmware/vcd-ext-sdk/tree/master/ui/api-client

After completing these steps, the seed plugin should build successfully.

**Comment by mgaruccio** [comment]
Thanks for the help, I tried running both commands but ended up getting an error(below) on the generate-sources command.  Attaching logs for both the install and generate-sources commands.  let me know if I should be creating a new issue for this.

[install.log](https://github.com/vmware/vcd-ext-sdk/files/2725356/install.log)
[generate.log](https://github.com/vmware/vcd-ext-sdk/files/2725358/generate.log)


`[ERROR] Failed to execute goal com.vmware.vcloud:vcd-bindings-maven-plugin:1.0.0:generate-typescript (default) on project vcd-typescript-api-client: Execution default of goal com.vmware.vcloud:vcd-bindings-maven-plugin:1.0.0:generate-typescript failed: A required class was missing while executing com.vmware.vcloud:vcd-bindings-maven-plugin:1.0.0:generate-typescript: javax/xml/bind/annotation/XmlType`

**Comment by mgaruccio** [comment]
Ahh ok perfect, after a few more false starts around things like dependencies I was able to get everything built and deploy the seed.  thank you for the help!

**Comment by jmoroski** [comment]
The backend prerequisites for @vcd/sdk are now published to publicly accessible Maven and NPM repositories. The SDK package has been updated to consume those directly instead of building by hand.
